// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1, arg2) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2);
}

export function LoadProfile(arg1, arg2) {
  return window['go']['main']['App']['LoadProfile'](arg1, arg2);
}

export function SendChat(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendChat'](arg1, arg2, arg3, arg4);
}

export function ServerConnect(arg1) {
  return window['go']['main']['App']['ServerConnect'](arg1);
}
