// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1:string,arg2:string):Promise<string>;

export function LoadProfile(arg1:string,arg2:string):Promise<string>;

export function SendChat(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ServerConnect(arg1:string):Promise<string>;
